// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaChannel) DeepCopyInto(out *KnativeEventingKafkaChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaChannel.
func (in *KnativeEventingKafkaChannel) DeepCopy() *KnativeEventingKafkaChannel {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeEventingKafkaChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaChannelList) DeepCopyInto(out *KnativeEventingKafkaChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnativeEventingKafkaChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaChannelList.
func (in *KnativeEventingKafkaChannelList) DeepCopy() *KnativeEventingKafkaChannelList {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeEventingKafkaChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaChannelSpec) DeepCopyInto(out *KnativeEventingKafkaChannelSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaChannelSpec.
func (in *KnativeEventingKafkaChannelSpec) DeepCopy() *KnativeEventingKafkaChannelSpec {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaChannelStatus) DeepCopyInto(out *KnativeEventingKafkaChannelStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaChannelStatus.
func (in *KnativeEventingKafkaChannelStatus) DeepCopy() *KnativeEventingKafkaChannelStatus {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaSource) DeepCopyInto(out *KnativeEventingKafkaSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaSource.
func (in *KnativeEventingKafkaSource) DeepCopy() *KnativeEventingKafkaSource {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeEventingKafkaSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaSourceList) DeepCopyInto(out *KnativeEventingKafkaSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnativeEventingKafkaSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaSourceList.
func (in *KnativeEventingKafkaSourceList) DeepCopy() *KnativeEventingKafkaSourceList {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeEventingKafkaSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaSourceSpec) DeepCopyInto(out *KnativeEventingKafkaSourceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaSourceSpec.
func (in *KnativeEventingKafkaSourceSpec) DeepCopy() *KnativeEventingKafkaSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeEventingKafkaSourceStatus) DeepCopyInto(out *KnativeEventingKafkaSourceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeEventingKafkaSourceStatus.
func (in *KnativeEventingKafkaSourceStatus) DeepCopy() *KnativeEventingKafkaSourceStatus {
	if in == nil {
		return nil
	}
	out := new(KnativeEventingKafkaSourceStatus)
	in.DeepCopyInto(out)
	return out
}
